/**
 * Bundled base card catalog (Batch D2).
 * Generated from quantum-collectors-card-data.json (D1 authoritative Firebase export).
 * Runtime source of truth for base definitions — do NOT fetch the root JSON at runtime.
 * Firebase /cards is overrides + Firebase-only additions until D4 migration.
 */

export const BASE_CARD_COUNT = 125;

/** @type {ReadonlyArray<object>} */
export const BASE_CARD_DEFINITIONS = Object.freeze(
  [
  {
    "id": "card_moza32gh3g93",
    "name": "Isaac Newton",
    "rarity": "legendary",
    "type": "scientist",
    "field": "Physics",
    "effect": "Gravity Master",
    "image": "",
    "flavor": "Formulated the laws of motion and universal gravitation, and co-invented calculus — most of it before age 26.",
    "imageUrl": "",
    "keyFact": "Formulated the laws of motion and universal gravitation, and co-invented calculus — most of it before age 26.",
    "enabled": true
  },
  {
    "id": "card_moza32gjulrs",
    "name": "Marie Curie",
    "rarity": "legendary",
    "type": "scientist",
    "field": "Radioactivity",
    "effect": "Radioactive Boost",
    "image": "",
    "flavor": "The only person ever to win Nobel Prizes in two different sciences — Physics (1903) and Chemistry (1911).",
    "imageUrl": "",
    "keyFact": "The only person ever to win Nobel Prizes in two different sciences — Physics (1903) and Chemistry (1911).",
    "enabled": true
  },
  {
    "id": "card_moza32gjvdwj",
    "name": "Albert Einstein",
    "rarity": "legendary",
    "type": "scientist",
    "field": "Physics",
    "effect": "Relativity Warp",
    "image": "",
    "flavor": "E=mc². Changed our understanding of space, time, and energy forever.",
    "imageUrl": "",
    "keyFact": "E=mc². Changed our understanding of space, time, and energy forever.",
    "enabled": true
  },
  {
    "id": "card_moza32gkcro8",
    "name": "Nikola Tesla",
    "rarity": "epic",
    "type": "scientist",
    "field": "Electromagnetism",
    "effect": "Electric Surge",
    "image": "",
    "flavor": "Invented the AC induction motor and transformer, making the modern electrical power grid possible — despite dying penniless.",
    "imageUrl": "",
    "keyFact": "Invented the AC induction motor and transformer, making the modern electrical power grid possible — despite dying penniless.",
    "enabled": true
  },
  {
    "id": "card_moza32gldyqh",
    "name": "Niels Bohr",
    "rarity": "epic",
    "type": "scientist",
    "field": "Quantum Physics",
    "effect": "Quantum Shell",
    "image": "",
    "flavor": "Niels Bohr developed a new model of the atom that helped launch the modern understanding of quantum physics.",
    "imageUrl": "",
    "keyFact": "Niels Bohr developed a new model of the atom that helped launch the modern understanding of quantum physics.",
    "enabled": true
  },
  {
    "id": "card_moza32gmda3a",
    "name": "Richard Feynman",
    "rarity": "epic",
    "type": "scientist",
    "field": "Quantum Electrodynamics",
    "effect": "Diagram Draw",
    "image": "",
    "flavor": "Invented Feynman diagrams to visualize quantum interactions, and famously diagnosed the Challenger disaster using a rubber ring in ice water.",
    "imageUrl": "",
    "keyFact": "Invented Feynman diagrams to visualize quantum interactions, and famously diagnosed the Challenger disaster using a rubber ring in ice water.",
    "enabled": true
  },
  {
    "id": "card_moza32gntucz",
    "name": "Stephen Hawking",
    "rarity": "epic",
    "type": "scientist",
    "field": "Cosmology",
    "effect": "X-Ray Vision",
    "image": "",
    "flavor": "Proved that black holes emit thermal radiation — now called Hawking Radiation — while living with ALS for 55 years.",
    "imageUrl": "",
    "keyFact": "Proved that black holes emit thermal radiation — now called Hawking Radiation — while living with ALS for 55 years.",
    "enabled": true
  },
  {
    "id": "card_moza32gp7umy",
    "name": "Paul Dirac",
    "rarity": "rare",
    "type": "scientist",
    "field": "Quantum Field Theory",
    "effect": "Telescope Scan",
    "image": "",
    "flavor": "Paul Dirac combined quantum mechanics with relativity and predicted antimatter years before it was experimentally discovered.",
    "imageUrl": "",
    "keyFact": "Paul Dirac combined quantum mechanics with relativity and predicted antimatter years before it was experimentally discovered.",
    "enabled": true
  },
  {
    "id": "card_moza32gq1i3w",
    "name": "Edwin Hubble",
    "rarity": "rare",
    "type": "scientist",
    "field": "Astronomy & Cosmology",
    "effect": "Wave Unifier",
    "image": "",
    "flavor": "Edwin Hubble discovered that distant galaxies are moving away from us, proving the universe is expanding.",
    "imageUrl": "",
    "keyFact": "Edwin Hubble discovered that distant galaxies are moving away from us, proving the universe is expanding.",
    "enabled": true
  },
  {
    "id": "card_moza32gquazh",
    "name": "Carl Sagan",
    "rarity": "rare",
    "type": "scientist",
    "field": "Astronomy & Science Communication",
    "effect": "Induction Field",
    "image": "",
    "flavor": "Carl Sagan inspired millions through science communication and helped popularize humanity’s cosmic exploration.",
    "imageUrl": "",
    "keyFact": "Carl Sagan inspired millions through science communication and helped popularize humanity’s cosmic exploration.",
    "enabled": true
  },
  {
    "id": "card_moza32gr25rg",
    "name": "Werner Heisenberg",
    "rarity": "rare",
    "type": "scientist",
    "field": "Quantum Mechanics",
    "effect": "Periodic Arrange",
    "image": "",
    "flavor": "Werner Heisenberg discovered the uncertainty principle, showing limits to how precisely particles can be measured.",
    "imageUrl": "",
    "keyFact": "Werner Heisenberg discovered the uncertainty principle, showing limits to how precisely particles can be measured.",
    "enabled": true
  },
  {
    "id": "card_moza32grubhh",
    "name": "Erwin Schrodinger",
    "rarity": "rare",
    "type": "scientist",
    "field": "Quantum Mechanics",
    "effect": "Algorithm Prime",
    "image": "",
    "flavor": "Erwin Schrödinger helped develop wave mechanics and became famous for the Schrödinger’s cat quantum thought experiment.",
    "imageUrl": "",
    "keyFact": "Erwin Schrödinger helped develop wave mechanics and became famous for the Schrödinger’s cat quantum thought experiment.",
    "enabled": true
  },
  {
    "id": "card_moza32grv00k",
    "name": "Johannes Kepler",
    "rarity": "rare",
    "type": "scientist",
    "field": "Planetary Motion",
    "effect": "Uncertainty",
    "image": "",
    "flavor": "Johannes Kepler discovered the mathematical laws that describe how planets orbit the Sun.",
    "imageUrl": "",
    "keyFact": "Johannes Kepler discovered the mathematical laws that describe how planets orbit the Sun.",
    "enabled": true
  },
  {
    "id": "card_moza32gs2ocf",
    "name": "Wolfgang Pauli",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Quantum Physics",
    "effect": "Nuclear Split",
    "image": "",
    "flavor": "Wolfgang Pauli developed the exclusion principle, explaining why electrons occupy unique quantum states.",
    "imageUrl": "",
    "keyFact": "Wolfgang Pauli developed the exclusion principle, explaining why electrons occupy unique quantum states.",
    "enabled": true
  },
  {
    "id": "card_moza32gsgrvi",
    "name": "Satyendra Nath Bose",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Quantum Statistics",
    "effect": "Spring Force",
    "image": "",
    "flavor": "Satyendra Nath Bose’s work with Einstein led to the discovery of bosons and Bose–Einstein condensates.",
    "imageUrl": "",
    "keyFact": "Satyendra Nath Bose’s work with Einstein led to the discovery of bosons and Bose–Einstein condensates.",
    "enabled": true
  },
  {
    "id": "card_moza32gsv6vl",
    "name": "James Clerk Maxwell",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Electromagnetism",
    "effect": "",
    "image": "",
    "flavor": "James Clerk Maxwell unified electricity, magnetism, and light into one set of equations, revealing that light is an electromagnetic wave.",
    "imageUrl": "",
    "keyFact": "James Clerk Maxwell unified electricity, magnetism, and light into one set of equations, revealing that light is an electromagnetic wave.",
    "enabled": true
  },
  {
    "id": "card_moza32gtgio7",
    "name": "Ernest Rutherford",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Nuclear Physics",
    "effect": "Lightning Rod",
    "image": "",
    "flavor": "Ernest Rutherford discovered the atomic nucleus and helped reveal the internal structure of atoms.",
    "imageUrl": "",
    "keyFact": "Ernest Rutherford discovered the atomic nucleus and helped reveal the internal structure of atoms.",
    "enabled": true
  },
  {
    "id": "card_moza32gtu80f",
    "name": "Louis de Broglie",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Wave Mechanics",
    "effect": "Orbit Predict",
    "image": "",
    "flavor": "Louis de Broglie proposed that matter behaves like waves, helping shape quantum mechanics.",
    "imageUrl": "",
    "keyFact": "Louis de Broglie proposed that matter behaves like waves, helping shape quantum mechanics.",
    "enabled": true
  },
  {
    "id": "card_moza32gulh56",
    "name": "Dark Energy",
    "rarity": "rare",
    "type": "concept",
    "field": "Cosmology",
    "effect": "Pull Force",
    "image": "",
    "flavor": "Dark energy is the mysterious cause of the universe's accelerating expansion, driving galaxies ever farther apart.",
    "imageUrl": "",
    "keyFact": "Dark energy is the mysterious cause of the universe's accelerating expansion, driving galaxies ever farther apart.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Improves the quality of research, leading to more Research Points."
  },
  {
    "id": "card_moza32gvusy4",
    "name": "Dark Matter",
    "rarity": "epic",
    "type": "concept",
    "field": "Astrophysics",
    "effect": "Energy Shield",
    "image": "",
    "flavor": "Dark matter is invisible, but its gravity shapes galaxies and the large-scale structure of the universe.",
    "imageUrl": "",
    "keyFact": "Dark matter is invisible, but its gravity shapes galaxies and the large-scale structure of the universe.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Improves the quality of research, leading to more Research Points."
  },
  {
    "id": "card_moza32gvv2ch",
    "name": "CERN",
    "rarity": "rare",
    "type": "concept",
    "field": "Reserach Organization",
    "effect": "Spectrum Blast",
    "image": "",
    "flavor": "CERN is home to the Large Hadron Collider, where scientists study the fundamental particles and forces that shape our universe.",
    "imageUrl": "",
    "keyFact": "CERN is home to the Large Hadron Collider, where scientists study the fundamental particles and forces that shape our universe.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Improves the quality of research, leading to more Research Points."
  },
  {
    "id": "card_moza32gvxppt",
    "name": "Antimatter",
    "rarity": "epic",
    "type": "concept",
    "field": "Particle Physics",
    "effect": "Chaos Increase",
    "image": "",
    "flavor": "When antimatter meets normal matter, both are completely converted into pure energy.",
    "imageUrl": "",
    "keyFact": "When antimatter meets normal matter, both are completely converted into pure energy.",
    "enabled": true,
    "conceptType": "breakthrough",
    "flavorText": "This provides a chance of discovering something extraordinary."
  },
  {
    "id": "card_moza32gwvahy",
    "name": "The Big Bang",
    "rarity": "legendary",
    "type": "concept",
    "field": "Cosmology",
    "effect": "Light Speed",
    "image": "",
    "flavor": "The universe began in an incredibly hot, dense state, and space has been expanding ever since.",
    "imageUrl": "",
    "keyFact": "The universe began in an incredibly hot, dense state, and space has been expanding ever since.",
    "enabled": true,
    "conceptType": "breakthrough",
    "flavorText": "A breakthrough of legendary proportions, this provides a chance of discovering something extraordinary."
  },
  {
    "id": "card_moza32h1irje",
    "name": "LIGO Observatory",
    "rarity": "rare",
    "type": "concept",
    "field": "Experimental Physics",
    "effect": "",
    "image": "",
    "flavor": "LIGO detects gravitational waves by measuring changes in spacetime smaller than one ten-thousandth the width of a proton.",
    "imageUrl": "",
    "keyFact": "LIGO detects gravitational waves by measuring changes in spacetime smaller than one ten-thousandth the width of a proton.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_moza32h1pfxd",
    "name": "Apollo Program",
    "rarity": "rare",
    "type": "concept",
    "field": "Space Exploration",
    "effect": "",
    "image": "",
    "flavor": "The Apollo Program landed the first humans on the Moon, marking the beginning of humanity's exploration beyond Earth.",
    "imageUrl": "",
    "keyFact": "The Apollo Program landed the first humans on the Moon, marking the beginning of humanity's exploration beyond Earth.",
    "enabled": true,
    "conceptType": "breakthrough",
    "flavorText": "This provides a chance of discovering something extraordinary."
  },
  {
    "id": "card_moza32h4h32i",
    "name": "Event Horizon",
    "rarity": "rare",
    "type": "concept",
    "field": "Astrophysics",
    "effect": "Heat Engine",
    "image": "",
    "flavor": "The event horizon marks the boundary beyond which not even light can escape a black hole.",
    "imageUrl": "",
    "keyFact": "The event horizon marks the boundary beyond which not even light can escape a black hole.",
    "enabled": true,
    "conceptType": "risk",
    "flavorText": "A greater reward comes with greater risk."
  },
  {
    "id": "card_moza32h51fsv",
    "name": "Black Hole",
    "rarity": "legendary",
    "type": "concept",
    "field": "Astrophysics",
    "effect": "Both States",
    "image": "",
    "flavor": "A black hole's gravity is so powerful that once anything crosses the event horizon, not even light can escape.",
    "imageUrl": "",
    "keyFact": "A black hole's gravity is so powerful that once anything crosses the event horizon, not even light can escape.",
    "enabled": true,
    "conceptType": "risk",
    "flavorText": "A greater reward comes with greater risk, and there's nothing more risky than a black hole."
  },
  {
    "id": "card_mp8m72f7h910",
    "name": "Nobel Prize",
    "rarity": "legendary",
    "type": "concept",
    "field": "Scientific Achievement",
    "effect": "",
    "image": "",
    "flavor": "The Nobel Prize in Physics recognizes discoveries that have transformed our understanding of the universe.",
    "imageUrl": "",
    "keyFact": "The Nobel Prize in Physics recognizes discoveries that have transformed our understanding of the universe.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Aspiring for a Nobel prize can elevate anyone to greater heights, increasing the effectiveness of their research."
  },
  {
    "id": "card_mpb9dc1iw18d",
    "name": "Dyson Sphere",
    "rarity": "epic",
    "type": "concept",
    "field": "Theoretical Megastructure",
    "effect": "",
    "image": "",
    "flavor": "A Dyson Sphere is a hypothetical megastructure built to capture nearly all of a star's energy.",
    "imageUrl": "",
    "keyFact": "A Dyson Sphere is a hypothetical megastructure built to capture nearly all of a star's energy.",
    "enabled": true,
    "conceptType": "breakthrough",
    "flavorText": "This provides a chance of discovering something extraordinary."
  },
  {
    "id": "card_mpb9eeqlx6n5",
    "name": "General Relativity",
    "rarity": "epic",
    "type": "concept",
    "field": "Theoretical Physics",
    "effect": "",
    "image": "",
    "flavor": "Massive objects curve space and time, creating what we experience as gravity.",
    "imageUrl": "",
    "keyFact": "Massive objects curve space and time, creating what we experience as gravity.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_mpb9gmc9pg5u",
    "name": "Gravitational Waves",
    "rarity": "epic",
    "type": "concept",
    "field": "Astrophysics",
    "effect": "",
    "image": "",
    "flavor": "Gravitational waves are ripples in spacetime created by some of the universe's most violent events.",
    "imageUrl": "",
    "keyFact": "Gravitational waves are ripples in spacetime created by some of the universe's most violent events.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Improves the quality of research, leading to more Research Points."
  },
  {
    "id": "card_mpbcc3zixp0h",
    "name": "NASA",
    "rarity": "epic",
    "type": "concept",
    "field": "Government Agency",
    "effect": "",
    "image": "",
    "flavor": "NASA advances science through exploration, engineering, and discoveries about Earth and the universe.",
    "imageUrl": "",
    "keyFact": "NASA advances science through exploration, engineering, and discoveries about Earth and the universe.",
    "enabled": true,
    "conceptType": "risk",
    "flavorText": "A greater reward comes with greater risk."
  },
  {
    "id": "card_mpbcd0737jks",
    "name": "Quantum Entanglement",
    "rarity": "epic",
    "type": "concept",
    "field": "Quantum Mechanics",
    "effect": "",
    "image": "",
    "flavor": "Two particles can become linked so that measuring one determines the state of the other, even across vast distances.",
    "imageUrl": "",
    "keyFact": "Two particles can become linked so that measuring one determines the state of the other, even across vast distances.",
    "enabled": true,
    "conceptType": "synergyBoost",
    "flavorText": "Improves the effective teamwork of scientists, making success more likely."
  },
  {
    "id": "card_mpbcgnxa76g9",
    "name": "Max Planck",
    "rarity": "epic",
    "type": "scientist",
    "field": "Quantum Theory",
    "effect": "",
    "image": "",
    "flavor": "Solved the \"ultraviolet catastrophe\" by proposing energy comes in discrete quanta — unwittingly founding quantum mechanics.",
    "imageUrl": "",
    "keyFact": "Solved the \"ultraviolet catastrophe\" by proposing energy comes in discrete quanta — unwittingly founding quantum mechanics.",
    "enabled": true
  },
  {
    "id": "card_mpbd0dzcpgq4",
    "name": "Galileo Galilei",
    "rarity": "epic",
    "type": "scientist",
    "field": "Astronomy & Mechanics",
    "effect": "",
    "image": "",
    "flavor": "Galileo used telescopes to observe the heavens, helping prove that Earth revolves around the Sun rather than the universe revolving around Earth.",
    "imageUrl": "",
    "keyFact": "Galileo used telescopes to observe the heavens, helping prove that Earth revolves around the Sun rather than the universe revolving around Earth.",
    "enabled": true
  },
  {
    "id": "card_mpbdcxu4clxg",
    "name": "Michael Faraday",
    "rarity": "epic",
    "type": "scientist",
    "field": "Electromagnetism",
    "effect": "",
    "image": "",
    "flavor": "Michael Faraday discovered electromagnetic induction, leading to electric motors, generators, and modern electricity production.",
    "imageUrl": "",
    "keyFact": "Michael Faraday discovered electromagnetic induction, leading to electric motors, generators, and modern electricity production.",
    "enabled": true
  },
  {
    "id": "card_mpbe4zq7k0ad",
    "name": "Enrico Fermi",
    "rarity": "rare",
    "type": "scientist",
    "field": "Nuclear Physics",
    "effect": "",
    "image": "",
    "flavor": "Enrico Fermi built the first controlled nuclear reactor, opening the door to nuclear power and the atomic age.",
    "imageUrl": "",
    "keyFact": "Enrico Fermi built the first controlled nuclear reactor, opening the door to nuclear power and the atomic age.",
    "enabled": true
  },
  {
    "id": "card_mpbe5bvrb5sy",
    "name": "J Robert Oppenheimer",
    "rarity": "rare",
    "type": "scientist",
    "field": "Nuclear Physics",
    "effect": "",
    "image": "",
    "flavor": "J. Robert Oppenheimer directed the Manhattan Project, leading the development of the first atomic bombs.",
    "imageUrl": "",
    "keyFact": "J. Robert Oppenheimer directed the Manhattan Project, leading the development of the first atomic bombs.",
    "enabled": true
  },
  {
    "id": "card_mpbe5s7dwnjh",
    "name": "Dmitri Mendeleev",
    "rarity": "rare",
    "type": "scientist",
    "field": "Chemistry",
    "effect": "",
    "image": "",
    "flavor": "Dmitri Mendeleev created the periodic table and correctly predicted elements that had not yet been discovered.",
    "imageUrl": "",
    "keyFact": "Dmitri Mendeleev created the periodic table and correctly predicted elements that had not yet been discovered.",
    "enabled": true
  },
  {
    "id": "card_mpbe65vypsuk",
    "name": "Rosalind Franklin",
    "rarity": "rare",
    "type": "scientist",
    "field": "Molecular Biology",
    "effect": "",
    "image": "",
    "flavor": "Rosalind Franklin’s X-ray images of DNA were critical to discovering the molecule’s double-helix structure.",
    "imageUrl": "",
    "keyFact": "Rosalind Franklin’s X-ray images of DNA were critical to discovering the molecule’s double-helix structure.",
    "enabled": true
  },
  {
    "id": "card_mpbe6r7hznuq",
    "name": "Neil deGrasse Tyson",
    "rarity": "rare",
    "type": "scientist",
    "field": "Astrophysics",
    "effect": "",
    "image": "",
    "flavor": "Neil deGrasse Tyson has inspired modern audiences through astronomy education, documentaries, and science outreach.",
    "imageUrl": "",
    "keyFact": "Neil deGrasse Tyson has inspired modern audiences through astronomy education, documentaries, and science outreach.",
    "enabled": true
  },
  {
    "id": "card_mpef1j2h1e2u",
    "name": "Multiverse Theory",
    "rarity": "rare",
    "type": "concept",
    "field": "Cosmology",
    "effect": "",
    "image": "",
    "flavor": "Multiverse theory suggests that our universe may be just one of many universes existing simultaneously.",
    "imageUrl": "",
    "keyFact": "Multiverse theory suggests that our universe may be just one of many universes existing simultaneously.",
    "enabled": true,
    "conceptType": "breakthrough",
    "flavorText": "This provides a chance of discovering something extraordinary."
  },
  {
    "id": "card_mpef2vjd3yky",
    "name": "Quantum Mechanics",
    "rarity": "rare",
    "type": "concept",
    "field": "Quantum Mechanics",
    "effect": "",
    "image": "",
    "flavor": "At the smallest scales, quantum mechanics predicts only the probabilities of where particles may be found.",
    "imageUrl": "",
    "keyFact": "At the smallest scales, quantum mechanics predicts only the probabilities of where particles may be found.",
    "enabled": true,
    "conceptType": "synergyBoost",
    "flavorText": "Improves the effective teamwork of scientists, making success more likely."
  },
  {
    "id": "card_mpefxlsv8gps",
    "name": "Special Relativity",
    "rarity": "rare",
    "type": "concept",
    "field": "Theoretical Physics",
    "effect": "",
    "image": "",
    "flavor": "Near the speed of light, moving clocks run slower and lengths contract relative to an outside observer.",
    "imageUrl": "",
    "keyFact": "Near the speed of light, moving clocks run slower and lengths contract relative to an outside observer.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_mpeg195m5224",
    "name": "String Theory",
    "rarity": "rare",
    "type": "concept",
    "field": "Theoretical Physics",
    "effect": "",
    "image": "",
    "flavor": "String theory suggests that different particles may simply be different vibrations of tiny fundamental strings.",
    "imageUrl": "",
    "keyFact": "String theory suggests that different particles may simply be different vibrations of tiny fundamental strings.",
    "enabled": true,
    "conceptType": "synergyBoost",
    "flavorText": "Improves the effective teamwork of scientists, making success more likely."
  },
  {
    "id": "card_mpeg2ekbctcf",
    "name": "Voyager Probe",
    "rarity": "rare",
    "type": "concept",
    "field": "Interstellar Exploration",
    "effect": "",
    "image": "",
    "flavor": "Voyager explored the giant planets before becoming the first spacecraft to reach interstellar space.",
    "imageUrl": "",
    "keyFact": "Voyager explored the giant planets before becoming the first spacecraft to reach interstellar space.",
    "enabled": true,
    "conceptType": "risk",
    "flavorText": "A greater reward comes with greater risk."
  },
  {
    "id": "card_mpeg3n315hkh",
    "name": "Wormholes",
    "rarity": "rare",
    "type": "concept",
    "field": "Theoretical Physics",
    "effect": "",
    "image": "",
    "flavor": "A wormhole is a theoretical shortcut through spacetime that could connect distant regions of the universe.",
    "imageUrl": "",
    "keyFact": "A wormhole is a theoretical shortcut through spacetime that could connect distant regions of the universe.",
    "enabled": true,
    "conceptType": "risk",
    "flavorText": "A greater reward comes with greater risk."
  },
  {
    "id": "card_mpehphsgwfd1",
    "name": "Subrahmanyan Chandrasekhar",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Stellar Physics",
    "effect": "",
    "image": "",
    "flavor": "Subrahmanyan Chandrasekhar discovered limits that determine whether stars become white dwarfs or collapse further.",
    "imageUrl": "",
    "keyFact": "Subrahmanyan Chandrasekhar discovered limits that determine whether stars become white dwarfs or collapse further.",
    "enabled": true
  },
  {
    "id": "card_mpo6aw4mtq16",
    "name": "Arthur Eddington",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Relativity & Astronomy",
    "effect": "",
    "image": "",
    "flavor": "Arthur Eddington confirmed Einstein’s relativity by observing starlight bending during a solar eclipse.",
    "imageUrl": "",
    "keyFact": "Arthur Eddington confirmed Einstein’s relativity by observing starlight bending during a solar eclipse.",
    "enabled": true
  },
  {
    "id": "card_mpo9l7zo2e22",
    "name": "Christiaan Huygens",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Optics & Astronomy",
    "effect": "",
    "image": "",
    "flavor": "Christiaan Huygens developed the wave theory of light and discovered Saturn’s moon Titan.",
    "imageUrl": "",
    "keyFact": "Christiaan Huygens developed the wave theory of light and discovered Saturn’s moon Titan.",
    "enabled": true
  },
  {
    "id": "card_mpobudhvhswl",
    "name": "Tycho Brahe",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Observational Astronomy",
    "effect": "",
    "image": "",
    "flavor": "Tycho Brahe made the most accurate planetary observations before the invention of the telescope.",
    "imageUrl": "",
    "keyFact": "Tycho Brahe made the most accurate planetary observations before the invention of the telescope.",
    "enabled": true
  },
  {
    "id": "card_mpod05vj8jqe",
    "name": "Henri Becquerel",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Radiation Physics",
    "effect": "",
    "image": "",
    "flavor": "Henri Becquerel discovered natural radioactivity by accident while studying uranium salts.",
    "imageUrl": "",
    "keyFact": "Henri Becquerel discovered natural radioactivity by accident while studying uranium salts.",
    "enabled": true
  },
  {
    "id": "card_mpod82ug6l7v",
    "name": "Erwin Chargaff",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Genetics & Biochemistry",
    "effect": "",
    "image": "",
    "flavor": "Erwin Chargaff discovered the pairing rules of DNA bases, helping reveal how genetic information is stored.",
    "imageUrl": "",
    "keyFact": "Erwin Chargaff discovered the pairing rules of DNA bases, helping reveal how genetic information is stored.",
    "enabled": true
  },
  {
    "id": "card_mpodh7liq5lb",
    "name": "Cecilia Payne-Gaposchkin",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Stellar Astronomy",
    "effect": "",
    "image": "",
    "flavor": "Cecilia Payne-Gaposchkin discovered that stars are composed mostly of hydrogen and helium.",
    "imageUrl": "",
    "keyFact": "Cecilia Payne-Gaposchkin discovered that stars are composed mostly of hydrogen and helium.",
    "enabled": true
  },
  {
    "id": "card_mpodqzvq07cl",
    "name": "Lise Meitner",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Nuclear Physics",
    "effect": "",
    "image": "",
    "flavor": "Lise Meitner helped explain nuclear fission, one of the most important discoveries in nuclear science.",
    "imageUrl": "",
    "keyFact": "Lise Meitner helped explain nuclear fission, one of the most important discoveries in nuclear science.",
    "enabled": true
  },
  {
    "id": "card_mpoe7nb7o0q5",
    "name": "Emmy Noether",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Mathematical Physics",
    "effect": "",
    "image": "",
    "flavor": "Emmy Noether showed that conservation laws in physics are connected to symmetries in nature.",
    "imageUrl": "",
    "keyFact": "Emmy Noether showed that conservation laws in physics are connected to symmetries in nature.",
    "enabled": true
  },
  {
    "id": "card_mpoewx1idenw",
    "name": "George Gamow",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Cosmology",
    "effect": "",
    "image": "",
    "flavor": "George Gamow helped develop early Big Bang theory models and explained how elements formed in the universe.",
    "imageUrl": "",
    "keyFact": "George Gamow helped develop early Big Bang theory models and explained how elements formed in the universe.",
    "enabled": true
  },
  {
    "id": "card_mpof6zdkybgg",
    "name": "Vera Rubin",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Dark Matter Research",
    "effect": "",
    "image": "",
    "flavor": "Vera Rubin discovered evidence that galaxies contain invisible dark matter affecting their rotation.",
    "imageUrl": "",
    "keyFact": "Vera Rubin discovered evidence that galaxies contain invisible dark matter affecting their rotation.",
    "enabled": true
  },
  {
    "id": "card_mpohx0mpaktg",
    "name": "Hendrik Lorentz",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Electromagnetism",
    "effect": "",
    "image": "",
    "flavor": "Hendrik Lorentz developed equations later used by Einstein in the theory of special relativity.",
    "imageUrl": "",
    "keyFact": "Hendrik Lorentz developed equations later used by Einstein in the theory of special relativity.",
    "enabled": true
  },
  {
    "id": "card_mpoi5kaitr3q",
    "name": "Hideki Yukawa",
    "rarity": "uncommon",
    "type": "scientist",
    "field": "Particle Physics",
    "effect": "",
    "image": "",
    "flavor": "Hideki Yukawa predicted mesons, particles responsible for helping bind atomic nuclei together.",
    "imageUrl": "",
    "keyFact": "Hideki Yukawa predicted mesons, particles responsible for helping bind atomic nuclei together.",
    "enabled": true
  },
  {
    "id": "card_mporlxgprf47",
    "name": "Cosmic Inflation",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Cosmology",
    "effect": "",
    "image": "",
    "flavor": "In its earliest moments, the universe expanded extraordinarily rapidly, becoming vastly larger in a tiny fraction of a second.",
    "imageUrl": "",
    "keyFact": "In its earliest moments, the universe expanded extraordinarily rapidly, becoming vastly larger in a tiny fraction of a second.",
    "enabled": true,
    "conceptType": "breakthrough",
    "flavorText": "This provides a chance of discovering something extraordinary."
  },
  {
    "id": "card_mporn44hdrsx",
    "name": "Electromagnetism",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Electromagnetism",
    "effect": "",
    "image": "",
    "flavor": "Electric currents produce magnetic fields that can be controlled to levitate and propel trains and many other machines.",
    "imageUrl": "",
    "keyFact": "Electric currents produce magnetic fields that can be controlled to levitate and propel trains and many other machines.",
    "enabled": true,
    "conceptType": "synergyBoost",
    "flavorText": "Improves the effective teamwork of scientists, making success more likely."
  },
  {
    "id": "card_mporo37da423",
    "name": "Entropy",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Thermodynamics",
    "effect": "",
    "image": "",
    "flavor": "There are far more ways for a system to be disordered than perfectly ordered, making highly ordered states difficult to maintain.",
    "imageUrl": "",
    "keyFact": "There are far more ways for a system to be disordered than perfectly ordered, making highly ordered states difficult to maintain.",
    "enabled": true,
    "conceptType": "risk",
    "flavorText": "A greater reward comes with greater risk."
  },
  {
    "id": "card_mporp0rdyfqy",
    "name": "Gravitational Lensing",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Astrophysics",
    "effect": "",
    "image": "",
    "flavor": "Gravity can bend the path of light, causing distant objects to appear stretched, distorted, or even duplicated.",
    "imageUrl": "",
    "keyFact": "Gravity can bend the path of light, causing distant objects to appear stretched, distorted, or even duplicated.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_mporq0vnhanv",
    "name": "Higgs Field",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Particle Physics",
    "effect": "",
    "image": "",
    "flavor": "The Higgs field gives many fundamental particles mass, allowing the universe to develop structure.",
    "imageUrl": "",
    "keyFact": "The Higgs field gives many fundamental particles mass, allowing the universe to develop structure.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_mporr329m11m",
    "name": "International Space Station",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Orbital Laboratory",
    "effect": "",
    "image": "",
    "flavor": "The International Space Station has been continuously inhabited since 2000, serving as a laboratory for research in microgravity.",
    "imageUrl": "",
    "keyFact": "The International Space Station has been continuously inhabited since 2000, serving as a laboratory for research in microgravity.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Improves the quality of research, leading to more Research Points."
  },
  {
    "id": "card_mpors6veae5u",
    "name": "James Webb Space Telescope",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Space Telescope",
    "effect": "",
    "image": "",
    "flavor": "Built with extraordinary precision, this telescope observes infrared light to reveal some of the earliest galaxies in the universe.",
    "imageUrl": "",
    "keyFact": "Built with extraordinary precision, this telescope observes infrared light to reveal some of the earliest galaxies in the universe.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Improves the quality of research, leading to more Research Points."
  },
  {
    "id": "card_mporxmvuvvct",
    "name": "Magnetic Fields",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Electromagnetism",
    "effect": "",
    "image": "",
    "flavor": "Magnetic fields exert forces that align magnetic materials, revealing the field's shape.",
    "imageUrl": "",
    "keyFact": "Magnetic fields exert forces that align magnetic materials, revealing the field's shape.",
    "enabled": true,
    "conceptType": "synergyBoost",
    "flavorText": "Improves the effective teamwork of scientists, making success more likely."
  },
  {
    "id": "card_mporyzqp6p8r",
    "name": "Nuclear Fission",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Nuclear Physics",
    "effect": "",
    "image": "",
    "flavor": "ach fission event releases neutrons that can split more atomic nuclei, creating a chain reaction.",
    "imageUrl": "",
    "keyFact": "ach fission event releases neutrons that can split more atomic nuclei, creating a chain reaction.",
    "enabled": true,
    "conceptType": "risk",
    "flavorText": "A greater reward comes with greater risk."
  },
  {
    "id": "card_mpos1b0zv5z6",
    "name": "Nuclear Forces",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Nuclear Physics",
    "effect": "",
    "image": "",
    "flavor": "The strong nuclear force binds protons and neutrons together, overcoming the electric repulsion between protons.",
    "imageUrl": "",
    "keyFact": "The strong nuclear force binds protons and neutrons together, overcoming the electric repulsion between protons.",
    "enabled": true,
    "conceptType": "synergyBoost",
    "flavorText": "Improves the effective teamwork of scientists, making success more likely."
  },
  {
    "id": "card_mpos2oai7kb2",
    "name": "Nuclear Fusion",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Nuclear Physics",
    "effect": "",
    "image": "",
    "flavor": "Fusion combines light atomic nuclei, releasing the enormous energy that powers every star.",
    "imageUrl": "",
    "keyFact": "Fusion combines light atomic nuclei, releasing the enormous energy that powers every star.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Improves the quality of research, leading to more Research Points."
  },
  {
    "id": "card_mpos4r9eyw0z",
    "name": "Particle Accelerators",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Particle Physics",
    "effect": "",
    "image": "",
    "flavor": "Electric fields accelerate particles to nearly the speed of light, allowing scientists to study matter at its smallest scales.",
    "imageUrl": "",
    "keyFact": "Electric fields accelerate particles to nearly the speed of light, allowing scientists to study matter at its smallest scales.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Improves the quality of research, leading to more Research Points."
  },
  {
    "id": "card_mpos6kkpvuou",
    "name": "Quantum Tunneling",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Quantum Mechanics",
    "effect": "",
    "image": "",
    "flavor": "Particles can sometimes pass through barriers without having enough energy to cross them normally.",
    "imageUrl": "",
    "keyFact": "Particles can sometimes pass through barriers without having enough energy to cross them normally.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_mpos7weazsk3",
    "name": "Solar Flares",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Astrophysics",
    "effect": "",
    "image": "",
    "flavor": "Solar flares release enormous amounts of energy and can affect satellites, communications, and power systems on Earth.",
    "imageUrl": "",
    "keyFact": "Solar flares release enormous amounts of energy and can affect satellites, communications, and power systems on Earth.",
    "enabled": true,
    "conceptType": "risk",
    "flavorText": "A greater reward comes with greater risk."
  },
  {
    "id": "card_mpos989m20si",
    "name": "Space-Time Curvature",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Theoretical Physics",
    "effect": "",
    "image": "",
    "flavor": "Massive objects curve space-time, causing matter and light to follow curved paths.",
    "imageUrl": "",
    "keyFact": "Massive objects curve space-time, causing matter and light to follow curved paths.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_mposcebuu07a",
    "name": "Superconductors",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Condensed Matter Physics",
    "effect": "",
    "image": "",
    "flavor": "When cooled below a critical temperature, superconductors conduct electricity without resistance and can levitate magnets.",
    "imageUrl": "",
    "keyFact": "When cooled below a critical temperature, superconductors conduct electricity without resistance and can levitate magnets.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_mposqedmggu9",
    "name": "Supernova",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Astrophysics",
    "effect": "",
    "image": "",
    "flavor": "Many of the elements found on Earth were created inside stars and spread through space by supernovae.",
    "imageUrl": "",
    "keyFact": "Many of the elements found on Earth were created inside stars and spread through space by supernovae.",
    "enabled": true,
    "conceptType": "breakthrough",
    "flavorText": "This provides a chance of discovering something extraordinary."
  },
  {
    "id": "card_mposrwvm6roy",
    "name": "Wave-Particle Duality",
    "rarity": "uncommon",
    "type": "concept",
    "field": "Quantum Mechanics",
    "effect": "",
    "image": "",
    "flavor": "Electrons and light can behave as both particles and waves, depending on how they are observed.",
    "imageUrl": "",
    "keyFact": "Electrons and light can behave as both particles and waves, depending on how they are observed.",
    "enabled": true,
    "conceptType": "synergyBoost",
    "flavorText": "Improves the effective teamwork of scientists, making success more likely."
  },
  {
    "id": "card_mpouka18pbhk",
    "name": "Acceleration",
    "rarity": "common",
    "type": "concept",
    "field": "Classical Mechanics",
    "effect": "",
    "image": "",
    "flavor": "Acceleration changes velocity by speeding up, slowing down, or changing direction.",
    "imageUrl": "",
    "keyFact": "Acceleration changes velocity by speeding up, slowing down, or changing direction.",
    "enabled": true,
    "conceptType": "risk",
    "flavorText": "A greater reward comes with greater risk."
  },
  {
    "id": "card_mpoulhbv0u52",
    "name": "Angular Momentum",
    "rarity": "common",
    "type": "concept",
    "field": "Classical Mechanics",
    "effect": "",
    "image": "",
    "flavor": "Pulling mass closer to the center increases spin, conserving angular momentum.",
    "imageUrl": "",
    "keyFact": "Pulling mass closer to the center increases spin, conserving angular momentum.",
    "enabled": true,
    "conceptType": "synergyBoost",
    "flavorText": "Improves the effective teamwork of scientists, making success more likely."
  },
  {
    "id": "card_mpoumlqjla8g",
    "name": "Bernoullis Principle",
    "rarity": "common",
    "type": "concept",
    "field": "Fluid Dynamics",
    "effect": "",
    "image": "",
    "flavor": "As a fluid moves faster, its pressure tends to decrease, helping explain how airfoils generate lift.",
    "imageUrl": "",
    "keyFact": "As a fluid moves faster, its pressure tends to decrease, helping explain how airfoils generate lift.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_mpov7ef1eh9f",
    "name": "Caltech",
    "rarity": "common",
    "type": "concept",
    "field": "Space & Physics Research",
    "effect": "",
    "image": "",
    "flavor": "Caltech scientists and engineers have made major contributions to physics, astronomy, engineering, and space exploration.",
    "imageUrl": "",
    "keyFact": "Caltech scientists and engineers have made major contributions to physics, astronomy, engineering, and space exploration.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_mpov8du3wd6x",
    "name": "Chaos Theory",
    "rarity": "common",
    "type": "concept",
    "field": "Mathematical Physics",
    "effect": "",
    "image": "",
    "flavor": "Small differences in starting conditions can lead to dramatically different outcomes in chaotic systems.",
    "imageUrl": "",
    "keyFact": "Small differences in starting conditions can lead to dramatically different outcomes in chaotic systems.",
    "enabled": true,
    "conceptType": "risk",
    "flavorText": "A greater reward comes with greater risk."
  },
  {
    "id": "card_mpov9ecjf1tn",
    "name": "Cryogenics",
    "rarity": "common",
    "type": "concept",
    "field": "Low Temperature Physics",
    "effect": "",
    "image": "",
    "flavor": "Cooling materials to cryogenic temperatures can drastically change their physical properties and behavior.",
    "imageUrl": "",
    "keyFact": "Cooling materials to cryogenic temperatures can drastically change their physical properties and behavior.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_mpovaeszfrlg",
    "name": "Doppler Effect",
    "rarity": "common",
    "type": "concept",
    "field": "Wave Physics",
    "effect": "",
    "image": "",
    "flavor": "Waves change frequency depending on whether the source is moving toward or away from you.",
    "imageUrl": "",
    "keyFact": "Waves change frequency depending on whether the source is moving toward or away from you.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Improves the quality of research, leading to more Research Points."
  },
  {
    "id": "card_mpovctvg779f",
    "name": "Electric Fields",
    "rarity": "common",
    "type": "concept",
    "field": "Electromagnetism",
    "effect": "",
    "image": "",
    "flavor": "Electric fields exert forces on charged objects, even without physical contact.",
    "imageUrl": "",
    "keyFact": "Electric fields exert forces on charged objects, even without physical contact.",
    "enabled": true,
    "conceptType": "synergyBoost",
    "flavorText": "Improves the effective teamwork of scientists, making success more likely."
  },
  {
    "id": "card_mpovdtybdkjx",
    "name": "Energy Conservation",
    "rarity": "common",
    "type": "concept",
    "field": "Classical Mechanics",
    "effect": "",
    "image": "",
    "flavor": "Energy can change form or move between objects, but the total amount remains constant.",
    "imageUrl": "",
    "keyFact": "Energy can change form or move between objects, but the total amount remains constant.",
    "enabled": true,
    "conceptType": "synergyBoost",
    "flavorText": "Improves the effective teamwork of scientists, making success more likely."
  },
  {
    "id": "card_mpovf190l2k0",
    "name": "Fermilab",
    "rarity": "common",
    "type": "concept",
    "field": "Particle Physics",
    "effect": "",
    "image": "",
    "flavor": "Fermilab uses powerful particle accelerators to explore the fundamental particles and forces that make up our universe.",
    "imageUrl": "",
    "keyFact": "Fermilab uses powerful particle accelerators to explore the fundamental particles and forces that make up our universe.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Improves the quality of research, leading to more Research Points."
  },
  {
    "id": "card_mpovgt3vl0xg",
    "name": "Gravity",
    "rarity": "common",
    "type": "concept",
    "field": "Classical Mechanics",
    "effect": "",
    "image": "",
    "flavor": "Gravity pulls all objects together, causing planets to orbit and a feather and hammer to accelerate equally in a vacuum.",
    "imageUrl": "",
    "keyFact": "Gravity pulls all objects together, causing planets to orbit and a feather and hammer to accelerate equally in a vacuum.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_mpoviftwq199",
    "name": "Hubble Space Telescope",
    "rarity": "common",
    "type": "concept",
    "field": "Space Telescope",
    "effect": "",
    "image": "",
    "flavor": "The Hubble Space Telescope captured some of the clearest images ever taken of the distant universe.",
    "imageUrl": "",
    "keyFact": "The Hubble Space Telescope captured some of the clearest images ever taken of the distant universe.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_mpovjh448q6s",
    "name": "Laser Interference",
    "rarity": "common",
    "type": "concept",
    "field": "Optics",
    "effect": "",
    "image": "",
    "flavor": "Interference patterns from lasers can measure distances with extraordinary precision.",
    "imageUrl": "",
    "keyFact": "Interference patterns from lasers can measure distances with extraordinary precision.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Improves the quality of research, leading to more Research Points."
  },
  {
    "id": "card_mpovl7gk8iam",
    "name": "MIT",
    "rarity": "common",
    "type": "concept",
    "field": "Engineering/Technology",
    "effect": "",
    "image": "",
    "flavor": "MIT researchers have contributed to advances in radar, computing, artificial intelligence, and many other fields of science and engineering.",
    "imageUrl": "",
    "keyFact": "MIT researchers have contributed to advances in radar, computing, artificial intelligence, and many other fields of science and engineering.",
    "enabled": true,
    "conceptType": "synergyBoost",
    "flavorText": "Improves the effective teamwork of scientists, making success more likely."
  },
  {
    "id": "card_mpovmq30yyii",
    "name": "Orbital Mechanics",
    "rarity": "common",
    "type": "concept",
    "field": "Classical Mechanics",
    "effect": "",
    "image": "",
    "flavor": "Objects in orbit constantly fall toward a body but move forward fast enough to keep missing it.",
    "imageUrl": "",
    "keyFact": "Objects in orbit constantly fall toward a body but move forward fast enough to keep missing it.",
    "enabled": true,
    "conceptType": "synergyBoost",
    "flavorText": "Improves the effective teamwork of scientists, making success more likely."
  },
  {
    "id": "card_mpovoibwydpg",
    "name": "Photon Emission",
    "rarity": "common",
    "type": "concept",
    "field": "Quantum Physics",
    "effect": "",
    "image": "",
    "flavor": "Excited atoms emit photons when electrons drop to lower energy levels.",
    "imageUrl": "",
    "keyFact": "Excited atoms emit photons when electrons drop to lower energy levels.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Improves the quality of research, leading to more Research Points."
  },
  {
    "id": "card_mpovpn1wd4an",
    "name": "Pressure",
    "rarity": "common",
    "type": "concept",
    "field": "Fluid Dynamics",
    "effect": "",
    "image": "",
    "flavor": "Pressure is force applied over an area, allowing concentrated forces to produce dramatic effects.",
    "imageUrl": "",
    "keyFact": "Pressure is force applied over an area, allowing concentrated forces to produce dramatic effects.",
    "enabled": true,
    "conceptType": "risk",
    "flavorText": "A greater reward comes with greater risk."
  },
  {
    "id": "card_mpovqk2scp6a",
    "name": "Radiation Shielding",
    "rarity": "common",
    "type": "concept",
    "field": "Nuclear Physics",
    "effect": "",
    "image": "",
    "flavor": "Dense materials can absorb or deflect harmful radiation, reducing the amount that passes through.",
    "imageUrl": "",
    "keyFact": "Dense materials can absorb or deflect harmful radiation, reducing the amount that passes through.",
    "enabled": true,
    "conceptType": "risk",
    "flavorText": "A greater reward comes with greater risk."
  },
  {
    "id": "card_mpovrtg4yejx",
    "name": "Radio Telescopes",
    "rarity": "common",
    "type": "concept",
    "field": "Astronomy",
    "effect": "",
    "image": "",
    "flavor": "Radio telescopes detect radio waves from space, allowing astronomers to study objects that may be invisible in ordinary light.",
    "imageUrl": "",
    "keyFact": "Radio telescopes detect radio waves from space, allowing astronomers to study objects that may be invisible in ordinary light.",
    "enabled": true,
    "conceptType": "breakthrough",
    "flavorText": "This provides a chance of discovering something extraordinary."
  },
  {
    "id": "card_mpovt5qsjt31",
    "name": "Redshift",
    "rarity": "common",
    "type": "concept",
    "field": "Astrophysics",
    "effect": "",
    "image": "",
    "flavor": "Light from objects moving away from us is stretched to longer wavelengths, shifting toward the red end of the spectrum.",
    "imageUrl": "",
    "keyFact": "Light from objects moving away from us is stretched to longer wavelengths, shifting toward the red end of the spectrum.",
    "enabled": true,
    "conceptType": "researchBoost",
    "flavorText": "Improves the quality of research, leading to more Research Points."
  },
  {
    "id": "card_mpovucf0ohjn",
    "name": "Refraction",
    "rarity": "common",
    "type": "concept",
    "field": "Optics",
    "effect": "",
    "image": "",
    "flavor": "Refraction bends light by changing its speed as it passes between different materials.",
    "imageUrl": "",
    "keyFact": "Refraction bends light by changing its speed as it passes between different materials.",
    "enabled": true,
    "conceptType": "difficultyReduction",
    "flavorText": "Simplifies the challenge, leading to a greater chance of success."
  },
  {
    "id": "card_mpovvfno77kf",
    "name": "Thermal Radiation",
    "rarity": "common",
    "type": "concept",
    "field": "Thermodynamics",
    "effect": "",
    "image": "",
    "flavor": "Hot objects emit thermal radiation, glowing brighter and shifting color as their temperature rises.",
    "imageUrl": "",
    "keyFact": "Hot objects emit thermal radiation, glowing brighter and shifting color as their temperature rises.",
    "enabled": true,
    "conceptType": "breakthrough",
    "flavorText": "This provides a chance of discovering something extraordinary."
  },
  {
    "id": "card_mpovwlo4137l",
    "name": "Time Dilation",
    "rarity": "common",
    "type": "concept",
    "field": "Relativity",
    "effect": "",
    "image": "",
    "flavor": "Time passes at different rates depending on speed and gravity, as predicted by Einstein’s theory of relativity.",
    "imageUrl": "",
    "keyFact": "Time passes at different rates depending on speed and gravity, as predicted by Einstein’s theory of relativity.",
    "enabled": true,
    "conceptType": "breakthrough",
    "flavorText": "This provides a chance of discovering something extraordinary."
  },
  {
    "id": "card_mpovxnxge5sk",
    "name": "Waves",
    "rarity": "common",
    "type": "concept",
    "field": "Wave Physics",
    "effect": "",
    "image": "",
    "flavor": "Waves transfer energy through a medium while creating patterns that reveal their motion.",
    "imageUrl": "",
    "keyFact": "Waves transfer energy through a medium while creating patterns that reveal their motion.",
    "enabled": true,
    "conceptType": "risk",
    "flavorText": "A greater reward comes with greater risk."
  },
  {
    "id": "card_mpoxk4gdjkhi",
    "name": "Andre-Marie Ampere",
    "rarity": "common",
    "type": "scientist",
    "field": "Electrodynamics",
    "effect": "",
    "image": "",
    "flavor": "André-Marie Ampère helped establish electromagnetism and gave his name to the unit of electric current.",
    "imageUrl": "",
    "keyFact": "André-Marie Ampère helped establish electromagnetism and gave his name to the unit of electric current.",
    "enabled": true
  },
  {
    "id": "card_mpoxm32l7r5t",
    "name": "Georg Ohm",
    "rarity": "common",
    "type": "scientist",
    "field": "Electricity",
    "effect": "",
    "image": "",
    "flavor": "Georg Ohm discovered the relationship between voltage, current, and resistance now known as Ohm’s Law.",
    "imageUrl": "",
    "keyFact": "Georg Ohm discovered the relationship between voltage, current, and resistance now known as Ohm’s Law.",
    "enabled": true
  },
  {
    "id": "card_mpoxv4rxen3d",
    "name": "Alessandro Volta",
    "rarity": "common",
    "type": "scientist",
    "field": "Electricity",
    "effect": "",
    "image": "",
    "flavor": "Alessandro Volta invented the first true electric battery, making continuous electrical current possible.",
    "imageUrl": "",
    "keyFact": "Alessandro Volta invented the first true electric battery, making continuous electrical current possible.",
    "enabled": true
  },
  {
    "id": "card_mpoy175hkpdl",
    "name": "Blaise Pascal",
    "rarity": "common",
    "type": "scientist",
    "field": "Fluid Mechanics",
    "effect": "",
    "image": "",
    "flavor": "Blaise Pascal studied pressure and fluids, helping lay the foundations of fluid mechanics and probability theory.",
    "imageUrl": "",
    "keyFact": "Blaise Pascal studied pressure and fluids, helping lay the foundations of fluid mechanics and probability theory.",
    "enabled": true
  },
  {
    "id": "card_mpoy7a7hcfdo",
    "name": "Evangelista Torricelli",
    "rarity": "common",
    "type": "scientist",
    "field": "Atmospheric Physics",
    "effect": "",
    "image": "",
    "flavor": "Evangelista Torricelli invented the barometer and helped prove that air has pressure.",
    "imageUrl": "",
    "keyFact": "Evangelista Torricelli invented the barometer and helped prove that air has pressure.",
    "enabled": true
  },
  {
    "id": "card_mpoyhyfhytv7",
    "name": "Robert Hooke",
    "rarity": "common",
    "type": "scientist",
    "field": "Mechanics & Microscopy",
    "effect": "",
    "image": "",
    "flavor": "Robert Hooke studied elasticity and microscopy, famously describing Hooke’s Law for springs.",
    "imageUrl": "",
    "keyFact": "Robert Hooke studied elasticity and microscopy, famously describing Hooke’s Law for springs.",
    "enabled": true
  },
  {
    "id": "card_mpoypc05h630",
    "name": "Antoine Lavoisier",
    "rarity": "common",
    "type": "scientist",
    "field": "Chemistry",
    "effect": "",
    "image": "",
    "flavor": "Antoine Lavoisier helped create modern chemistry and discovered the role of oxygen in combustion.",
    "imageUrl": "",
    "keyFact": "Antoine Lavoisier helped create modern chemistry and discovered the role of oxygen in combustion.",
    "enabled": true
  },
  {
    "id": "card_mpoystudkhz6",
    "name": "Georges Lemaitre",
    "rarity": "common",
    "type": "scientist",
    "field": "Cosmology",
    "effect": "",
    "image": "",
    "flavor": "Lemaître proposed that the universe began from a tiny, dense state and later expanded, helping lay the foundation for modern Big Bang theory.",
    "imageUrl": "",
    "keyFact": "Lemaître proposed that the universe began from a tiny, dense state and later expanded, helping lay the foundation for modern Big Bang theory.",
    "enabled": true
  },
  {
    "id": "card_mppigzvl8c8b",
    "name": "Freeman Dyson",
    "rarity": "common",
    "type": "scientist",
    "field": "Quantum Physics",
    "effect": "",
    "image": "",
    "flavor": "Dyson helped unify approaches to quantum electrodynamics, improving understanding of how light and matter interact.",
    "imageUrl": "",
    "keyFact": "Dyson helped unify approaches to quantum electrodynamics, improving understanding of how light and matter interact.",
    "enabled": true
  },
  {
    "id": "card_mppjfje067gn",
    "name": "Grace Hopper",
    "rarity": "common",
    "type": "scientist",
    "field": "Scientific Computing",
    "effect": "",
    "image": "",
    "flavor": "Grace Hopper helped develop early computer programming systems, making computers easier for scientists and engineers to use.",
    "imageUrl": "",
    "keyFact": "Grace Hopper helped develop early computer programming systems, making computers easier for scientists and engineers to use.",
    "enabled": true
  },
  {
    "id": "card_mppjr8iqmh1o",
    "name": "Chien-Shiung Wu",
    "rarity": "common",
    "type": "scientist",
    "field": "Experimental Physics",
    "effect": "",
    "image": "",
    "flavor": "Chien-Shiung Wu performed experiments that overturned a long-standing assumption in particle physics.",
    "imageUrl": "",
    "keyFact": "Chien-Shiung Wu performed experiments that overturned a long-standing assumption in particle physics.",
    "enabled": true
  },
  {
    "id": "card_mppjzlkd35sx",
    "name": "Maria Goeppert Mayer",
    "rarity": "common",
    "type": "scientist",
    "field": "Nuclear Physics",
    "effect": "",
    "image": "",
    "flavor": "Maria Goeppert Mayer developed the nuclear shell model explaining the structure of atomic nuclei.",
    "imageUrl": "",
    "keyFact": "Maria Goeppert Mayer developed the nuclear shell model explaining the structure of atomic nuclei.",
    "enabled": true
  },
  {
    "id": "card_mppkhhbwswn4",
    "name": "Leonhard Euler",
    "rarity": "common",
    "type": "scientist",
    "field": "Mathematics",
    "effect": "",
    "image": "",
    "flavor": "Leonhard Euler introduced mathematical notation and formulas still widely used in science today.",
    "imageUrl": "",
    "keyFact": "Leonhard Euler introduced mathematical notation and formulas still widely used in science today.",
    "enabled": true
  },
  {
    "id": "card_mppkkxnev2kf",
    "name": "Archimedes",
    "rarity": "common",
    "type": "scientist",
    "field": "Classical Mechanics",
    "effect": "",
    "image": "",
    "flavor": "Archimedes discovered principles of buoyancy and created inventions centuries ahead of his time.",
    "imageUrl": "",
    "keyFact": "Archimedes discovered principles of buoyancy and created inventions centuries ahead of his time.",
    "enabled": true
  },
  {
    "id": "card_mppkup1d0ikb",
    "name": "Aristotle",
    "rarity": "common",
    "type": "scientist",
    "field": "Natural Philosophy",
    "effect": "",
    "image": "",
    "flavor": "Aristotle shaped scientific thinking for nearly two thousand years through his writings on nature and logic.",
    "imageUrl": "",
    "keyFact": "Aristotle shaped scientific thinking for nearly two thousand years through his writings on nature and logic.",
    "enabled": true
  },
  {
    "id": "card_mpplcjr130vb",
    "name": "Nicolaus Copernicus",
    "rarity": "common",
    "type": "scientist",
    "field": "Astronomy",
    "effect": "",
    "image": "",
    "flavor": "Nicolaus Copernicus proposed that Earth and the planets orbit the Sun rather than Earth being the center of the universe.",
    "imageUrl": "",
    "keyFact": "Nicolaus Copernicus proposed that Earth and the planets orbit the Sun rather than Earth being the center of the universe.",
    "enabled": true
  },
  {
    "id": "card_mppn6im4n4ae",
    "name": "Benjamin Franklin",
    "rarity": "common",
    "type": "scientist",
    "field": "Electricity",
    "effect": "",
    "image": "",
    "flavor": "Benjamin Franklin pioneered the single-fluid theory of positive and negative charges, and invented both the lightning rod and bifocals.",
    "imageUrl": "",
    "keyFact": "Benjamin Franklin pioneered the single-fluid theory of positive and negative charges, and invented both the lightning rod and bifocals.",
    "enabled": true
  },
  {
    "id": "card_mppnbip912i8",
    "name": "Edmond Halley",
    "rarity": "common",
    "type": "scientist",
    "field": "Astronomy",
    "effect": "",
    "image": "",
    "flavor": "Edmond Halley predicted the return of the comet that now bears his name using mathematical astronomy.",
    "imageUrl": "",
    "keyFact": "Edmond Halley predicted the return of the comet that now bears his name using mathematical astronomy.",
    "enabled": true
  },
  {
    "id": "card_mppnl11mbn6z",
    "name": "Hedy Lamarr",
    "rarity": "common",
    "type": "scientist",
    "field": "Communications Technology",
    "effect": "",
    "image": "",
    "flavor": "Hedy Lamarr a Hollywood actress co-developed frequency-hopping technology that later contributed to Wi-Fi and Bluetooth systems.",
    "imageUrl": "",
    "keyFact": "Hedy Lamarr a Hollywood actress co-developed frequency-hopping technology that later contributed to Wi-Fi and Bluetooth systems.",
    "enabled": true
  },
  {
    "id": "card_mppod2d63ymo",
    "name": "John Dalton",
    "rarity": "common",
    "type": "scientist",
    "field": "Atomic Theory",
    "effect": "",
    "image": "",
    "flavor": "John Dalton developed one of the first modern atomic theories describing matter as combinations of atoms.",
    "imageUrl": "",
    "keyFact": "John Dalton developed one of the first modern atomic theories describing matter as combinations of atoms.",
    "enabled": true
  },
  {
    "id": "card_mppox8u4yty5",
    "name": "Pierre-Simon Laplace",
    "rarity": "common",
    "type": "scientist",
    "field": "Celestial Mechanics",
    "effect": "",
    "image": "",
    "flavor": "Pierre-Simon Laplace used mathematics to predict planetary motion and study the stability of the solar system.",
    "imageUrl": "",
    "keyFact": "Pierre-Simon Laplace used mathematics to predict planetary motion and study the stability of the solar system.",
    "enabled": true
  },
  {
    "id": "card_mppp36ey2rs7",
    "name": "Robert Boyle",
    "rarity": "common",
    "type": "scientist",
    "field": "Fluid Dynamics",
    "effect": "",
    "image": "",
    "flavor": "Robert Boyle discovered the relationship between gas pressure and volume, now known as Boyle’s Law.",
    "imageUrl": "",
    "keyFact": "Robert Boyle discovered the relationship between gas pressure and volume, now known as Boyle’s Law.",
    "enabled": true
  },
  {
    "id": "card_mpppbrbuh2qk",
    "name": "Thomas Young",
    "rarity": "common",
    "type": "scientist",
    "field": "Optics",
    "effect": "",
    "image": "",
    "flavor": "Thomas Young demonstrated light interference, helping prove that light behaves as a wave.",
    "imageUrl": "",
    "keyFact": "Thomas Young demonstrated light interference, helping prove that light behaves as a wave.",
    "enabled": true
  }
].map((c) => Object.freeze({ ...c })),
);
